config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/github/callback' => 'sessions#create'
  get '/landing' => 'recipes#landing'

  resources :users, only: [:new, :create] do
    resources :recipes, except: [:show, :edit, :update, :destroy]
  end
  resources :recipes, only: [:index, :show]
  resources :ingredients, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :quantities
  has_many :recipes, through: :quantities

  scope :by_name, -> { order(name: :asc) }

end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  validates :amount, presence: true

  accepts_nested_attributes_for :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :quantities
  has_many :ingredients, through: :quantities

  validates :name, :instructions, :time, presence: true

  accepts_nested_attributes_for :quantities

  def quantities_attributes=(quantities_attributes)
    self.quantities.destroy_all
    quantities_attributes.each do |key, value|
      if value["ingredient_attributes"]["name"] != ""
        ingredient = Ingredient.find_or_create_by(name: value["ingredient_attributes"]["name"])
        self.quantities.build(ingredient: ingredient, amount: value["amount"])
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_secure_password

  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }

  def self.find_or_create_by_omniauth(auth_hash)
    oauth_email = auth_hash["info"]["email"]
    self.where(email: oauth_email).first_or_create do |user|
      user.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to root_path unless session.include? :user_id
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :require_login

  def index
    @ingredients = Ingredient.by_name
    render json: @ingredients, status: 201

  end

  def show
    @ingredient = Ingredient.find_by(id: params[:id])
    render json: @ingredient, status: 201
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :require_login

  def landing
  end

  def index
    if params[:user_id] && current_user.id == params[:user_id].to_i
      @user = current_user
      @recipes = @user.recipes
      render json: @recipes, status: 201
    elsif params[:user_id]
      flash[:alert] = "You are not authorized to view this user's page."
      redirect_to recipes_path
    else
      @recipes = Recipe.all
      render json: @recipes, status: 201
    end
  end

  def new
    @user = current_user
    @recipe = Recipe.new(user_id: params[:user_id])
    10.times do
      quantity = @recipe.quantities.build
      quantity.build_ingredient
    end
    render :partial => 'recipes/form', :layout => false
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      render json: @recipe, status: 201
    else
      render json: @recipe, status: 406
    end
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    render json: @recipe, status: 201
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :user_id, :time, :instructions, quantities_attributes: [:amount, ingredient_attributes: [:name]])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      @user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = @user.id
      redirect_to landing_path
    else
      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to landing_path
      else
        flash[:alert] = "Something went wrong. Please try again."
        redirect_to login_path
      end
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to landing_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def plural_ingredients(recipe)
    pluralize(recipe.ingredient_count, "ingredient")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickAndEasyRecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div>
            <ul class="nav navbar-nav">
              <li><%= link_to "All Recipes", recipes_path, :id => "all-recipes-link" %></li>
              <li><%= link_to "Your Recipes", user_recipes_path(current_user), :id => "user-recipes-link" %></li>
              <li><%= link_to "Recipes by Ingredient", ingredients_path, :id => "ingredients-link" %></li>
              <li><%= link_to "New Recipe", new_user_recipe_path(current_user), :id => "new-recipe-link" %></li>
              <li><%= link_to "Logout", logout_path %></li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <h4>There were some errors.</h4>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/recipes/_flash_alert.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<h2>Create a New Recipe</h2>

<%= form_for [@user, @recipe] do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :time %><br>
  <%= f.number_field :time %> minutes <br>
  <%= f.label :ingredients %><br>
  <%= f.fields_for :quantities do |q| %>
    <%= q.label :amount %>
    <%= q.text_field :amount %>
    <%= q.fields_for :ingredient do |i| %>
      <%= i.label :name %>
      <%= i.text_field :name, list: "ingredients_autocomplete" %><br>
        <datalist id="ingredients_autocomplete">
          <% Ingredient.by_name.each do |ingredient| %>
            <option value="<%= ingredient.name %>">
          <% end %>
        </datalist>
    <% end %>
  <% end %>
  <%= f.label :instructions %><br>
  <%= f.text_area :instructions %><br>
  <%= f.submit 'Submit', :class=> 'btn btn-primary' %>
<% end %>

app/views/recipes/form.html.erb
<h2>Create a New Recipe</h2>

<%= form_for [@user, @recipe] do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :time %><br>
  <%= f.number_field :time %> minutes <br>
  <%= f.label :ingredients %><br>
  <%= f.fields_for :quantities do |q| %>
    <%= q.label :amount %>
    <%= q.text_field :amount %>
    <%= q.fields_for :ingredient do |i| %>
      <%= i.label :name %>
      <%= i.text_field :name, list: "ingredients_autocomplete" %><br>
        <datalist id="ingredients_autocomplete">
          <% Ingredient.by_name.each do |ingredient| %>
            <option value="<%= ingredient.name %>">
          <% end %>
        </datalist>
    <% end %>
  <% end %>
  <%= f.label :instructions %><br>
  <%= f.text_area :instructions %><br>
  <%= f.submit 'Submit', :class=> 'btn btn-primary' %>
<% end %>

app/views/recipes/landing.html.erb
<h1>Quick and Easy Recipes</h1>

<div id="landing-content">
  <h3><em>Use the navigation links above to display recipes.</em></h3>  
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<h3>Sign up for a new account below.</h3>

<%= render partial: "recipes/errors", locals: {object: @user} %>

<%= form_for @user do |f| %>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit 'Create a new account', :class=> 'btn btn-primary' %>
<% end %>

<%= link_to "Log in with Github", "/auth/github" %>

app/views/welcome/home.html.erb
<h1>Quick and Easy Recipes</h1>

<p>Welcome to Quick and Easy Recipes, a website where you can store and share, you guessed it, your quickest and easiest recipes! </p>

<h4>Please Sign In or Create an Account Below.</h4>

<p><%= link_to "Sign In", login_path %></p>
<p><%= link_to "Create an Account", new_user_path %></p>